added flutter example
AnomalyInnovations/serverless-stack-com pull request #606
Opened 2021-11-03 16:14 UTC by Manitej66

2021-11-04 08:01 UTC, fwang requested changes

2021-11-04 08:01 UTC, fwang commented on _examples/how-to-create-a-flutter-app-with-serverless.md
> +```
Got an error the `http` package is not found

<img width="728" alt="Screen Shot 2021-11-04 at 3 59 36 AM" src="https://user-images.githubusercontent.com/83515/140277888-9b03b873-3ae6-4986-a06e-ebbbe349f062.png">

2021-11-04 08:56 UTC, fwang commented
Here are the iOS screenshots.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-11-04 at 04 47 51](https://user-images.githubusercontent.com/83515/140285452-7bb7b820-acee-4653-b390-69c615574576.png)

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-11-04 at 04 50 09](https://user-images.githubusercontent.com/83515/140285469-78c65d71-9989-4edc-9d39-6a4c85e161e4.png)

2021-11-05 22:39 UTC, jayair commented
Thanks @Manitej66!

2021-11-05 22:39 UTC, merged